<?php 
//@group utmReports
$utmDataProvider = 
[
    /*
     * Positive tests
     */
    [
    'login'=>'welhome',
    'accountId'=>879,
    'siteId'=>1034,
    'beginDate'=>'2016-06-09',
    'endDate'=>'2016-06-09',
    'section'=>'UTM-метки',
    'utm_data'=>
        [
            [
            'begin_date'=>'2016-06-16',
            'end_date'=>'2016-06-16',
            'utm_filter'=>'UTM Content',
            'utm_data_to_check'=>
                [
                    [
                        'num_of_results'=>15,
                        'utm_report_data'=>
                        [
                            //'utm_name'=>' ',

                            [
                                'utm_name'=>' ',
                                'calls'=>'4Всегозапериод',
                                'unique_calls'=>'4Всегозапериод',
                                'target_calls'=>'3Всегозапериод',
                                'unique_target_calls'=>'3Всегозапериод',
                                'calls_in_work_time'=>'4Всегозапериод',
                                'online_requests'=>'0Всегозапериод',
                                'orders'=>'0Всегозапериод',
                                'visits'=>'210Всегозапериод',
                                'conversion_from_spec_or_garanty'=>'0/0Всегозапериод',
                                'calls_from_spec_or_garanty'=>'0/0Всегозапериод',
                                'conversion_to_calls_from_spec_or_garanty'=>'00Всегозапериод',
                                'conversion_to_orders'=>'-Всегозапериод',
                                'conversion_to_treatment'=>'1,43%Всегозапериод',
                                'conversion_from_YD'=>'207Всегозапериод',
                                'shows_YD_in_search'=>'4309Всегозапериод',
                                'shows_RSY'=>'573Всегозапериод',
                                'costs_YD'=>'6951,30Всегозапериод',
                                'costs_in_RSY'=>'19,80Всегозапериод',
                                'costs_to_show_in_search_YD'=>'6931,50Всегозапериод',
                                'conversion_from_google_adw'=>'0Всегозапериод',
                                'costs_google_adwords'=>'0,00Всегозапериод',
                                'num_of_sales'=>'0Всегозапериод',
                                'conversion_from_treatment_to_sale'=>'-Всегозапериод',
                                'cost_of_sale_CAC'=>'Всегозапериод',
                                'treatment'=>'3Всегозапериод',
                                'cost_of_treatment'=>'2317,10Всегозапериод',
                                'orders_on_calls'=>'0Всегозапериод',
                                'revenue_calls'=>'0Всегозапериод',
                                'total_revenue'=>'0Всегозапериод',
                                'ROI'=>'-Всегозапериод',
                                'DRR'=>'-Всегозапериод',
                                'shows_in_spec_placement'=>'-Всегозапериод',
                                'shows_in_waranty_YD'=>'-Всегозапериод',
                                'ration_of_shows_of_spec_or_warantyYD'=>'-Всегозапериод',
                                'num_of_visits_YM'=>'273Всегозапериод',
                                'failures_YM'=>'17,22%Среднеезапериод',
                                'average_length_of_session_YM'=>'78,98Среднеезапериод',
                                'depth_of_view_YM'=>'1,83Среднеезапериод',
                                'goal_YM_one'=>'17Всегозапериод',
                                'goal_YM_two'=>'82Всегозапериод',

                            ],
                            [
                                'utm_name'=>'premium.1',
                                'calls'=>'2',
                                'unique_calls'=>'2',
                                'target_calls'=>'2',
                                'unique_target_calls'=>'2',
                                'calls_in_work_time'=>'2',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'110',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'1,82%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'2',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'107',
                                'failures_YM'=>'14,95%',
                                'average_length_of_session_YM'=>'65,43',
                                'depth_of_view_YM'=>'1,73',
                                'goal_YM_one'=>'6',
                                'goal_YM_two'=>'15',

                            ],
                            [
                                'utm_name'=>'premium.2',
                                'calls'=>'2',
                                'unique_calls'=>'2',
                                'target_calls'=>'1',
                                'unique_target_calls'=>'1',
                                'calls_in_work_time'=>'2',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'55',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'1,82%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'1',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'57',
                                'failures_YM'=>'22,81%',
                                'average_length_of_session_YM'=>'85,96',
                                'depth_of_view_YM'=>'1,68',
                                'goal_YM_one'=>'4',
                                'goal_YM_two'=>'12',

                            ],
                            [
                                'utm_name'=>'premium.3',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'18',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'20',
                                'failures_YM'=>'30,00%',
                                'average_length_of_session_YM'=>'93,35',
                                'depth_of_view_YM'=>'1,90',
                                'goal_YM_one'=>'2',
                                'goal_YM_two'=>'2',

                            ],
                            [
                                'utm_name'=>'other.1',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'8',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'10',
                                'failures_YM'=>'20,00%',
                                'average_length_of_session_YM'=>'23,80',
                                'depth_of_view_YM'=>'1,40',
                                'goal_YM_one'=>'1',
                                'goal_YM_two'=>'2',

                            ],
                            [
                                'utm_name'=>'other.3',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'4',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'4',
                                'failures_YM'=>'25,00%',
                                'average_length_of_session_YM'=>'22,75',
                                'depth_of_view_YM'=>'1,75',
                                'goal_YM_one'=>'1',
                                'goal_YM_two'=>'0',

                            ],
                            [
                                'utm_name'=>'other.2',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'4',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'5',
                                'failures_YM'=>'0,00%',
                                'average_length_of_session_YM'=>'22,00',
                                'depth_of_view_YM'=>'1,20',
                                'goal_YM_one'=>'0',
                                'goal_YM_two'=>'0',

                            ],
                            [
                                'utm_name'=>'{PTYPE}.{POS}',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'2',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'--',
                                'failures_YM'=>'--',
                                'average_length_of_session_YM'=>'--',
                                'depth_of_view_YM'=>'--',
                                'goal_YM_one'=>'--',
                                'goal_YM_two'=>'--',

                            ],
                            [
                                'utm_name'=>'none.1',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'2',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'2',
                                'failures_YM'=>'0,00%',
                                'average_length_of_session_YM'=>'14,50',
                                'depth_of_view_YM'=>'1,00',
                                'goal_YM_one'=>'0',
                                'goal_YM_two'=>'0',

                            ],
                            [
                                'utm_name'=>'none.7',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'1',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'2',
                                'failures_YM'=>'0,00%',
                                'average_length_of_session_YM'=>'14,00',
                                'depth_of_view_YM'=>'1,00',
                                'goal_YM_one'=>'0',
                                'goal_YM_two'=>'0',

                            ],
                            [
                                'utm_name'=>'none.6',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'1',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'1',
                                'failures_YM'=>'0,00%',
                                'average_length_of_session_YM'=>'54,00',
                                'depth_of_view_YM'=>'2,00',
                                'goal_YM_one'=>'0',
                                'goal_YM_two'=>'0',

                            ],
                            [
                                'utm_name'=>'none.5',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'1',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'--',
                                'failures_YM'=>'--',
                                'average_length_of_session_YM'=>'--',
                                'depth_of_view_YM'=>'--',
                                'goal_YM_one'=>'--',
                                'goal_YM_two'=>'--',

                            ],
                            [
                                'utm_name'=>'none.2',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'1',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'1',
                                'failures_YM'=>'100,00%',
                                'average_length_of_session_YM'=>'0,00',
                                'depth_of_view_YM'=>'1,00',
                                'goal_YM_one'=>'0',
                                'goal_YM_two'=>'0',

                            ],
                            [
                                'utm_name'=>'none.16',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'1',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'1',
                                'failures_YM'=>'0,00%',
                                'average_length_of_session_YM'=>'27,00',
                                'depth_of_view_YM'=>'1,00',
                                'goal_YM_one'=>'0',
                                'goal_YM_two'=>'0',

                            ],
                            [
                                'utm_name'=>'none.0',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'1',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'1',
                                'failures_YM'=>'100,00%',
                                'average_length_of_session_YM'=>'0,00',
                                'depth_of_view_YM'=>'1,00',
                                'goal_YM_one'=>'0',
                                'goal_YM_two'=>'0',

                            ],
                            [
                                'utm_name'=>'[Пустое значение]',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'1',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'58',
                                'failures_YM'=>'10,34%',
                                'average_length_of_session_YM'=>'123,62',
                                'depth_of_view_YM'=>'2,41',
                                'goal_YM_one'=>'3',
                                'goal_YM_two'=>'51',

                            ],




                        ]
                    ],
                ]
            ],

        ],

    ],
    [
    'login'=>'admin',
    'accountId'=>5221,
    'siteId'=>4119,
    'beginDate'=>'2016-06-15',
    'endDate'=>'2016-06-21',
    'section'=>'UTM-метки',
    'utm_data'=>
         [
            [
            'begin_date'=>'2016-06-15',
            'end_date'=>'2016-06-21',
            'utm_filter'=>'UTM Medium',
            'utm_data_to_check'=>
                [
                    [
                        'num_of_results'=>2,
                        'utm_report_data'=>
                        [

                            [
                                'utm_name'=>' ',
                                'calls'=>'7Всегозапериод',
                                'unique_calls'=>'7Всегозапериод',
                                'target_calls'=>'7Всегозапериод',
                                'unique_target_calls'=>'7Всегозапериод',
                                'calls_in_work_time'=>'7Всегозапериод',
                                'online_requests'=>'2Всегозапериод',
                                'orders'=>'0Всегозапериод',
                                'visits'=>'519Всегозапериод',
                                'tags_and_categories'=>'4Всегозапериод',
                                'conversion_from_spec_or_garanty'=>'222/15Всегозапериод',
                                'calls_from_spec_or_garanty'=>'2/2Всегозапериод',
                                'conversion_to_calls_from_spec_or_garanty'=>'00Всегозапериод',
                                'conversion_to_orders'=>'-Всегозапериод',
                                'conversion_to_treatment'=>'1,73%Всегозапериод',
                                'conversion_from_YD'=>'555Всегозапериод',
                                'shows_YD_in_search'=>'62804Всегозапериод',
                                'shows_RSY'=>'84865Всегозапериод',
                                'costs_YD'=>'31476,60Всегозапериод',
                                'costs_in_RSY'=>'4661,70Всегозапериод',
                                'costs_to_show_in_search_YD'=>'26814,90Всегозапериод',
                                'conversion_from_google_adw'=>'416Всегозапериод',
                                'costs_google_adwords'=>'23660,44Всегозапериод',
                                'num_of_sales'=>'0Всегозапериод',
                                'conversion_from_treatment_to_sale'=>'-Всегозапериод',
                                'cost_of_sale_CAC'=>'Всегозапериод',
                                'treatment'=>'9Всегозапериод',
                                'cost_of_treatment'=>'6126,34Всегозапериод',
                                'orders_on_calls'=>'0Всегозапериод',
                                'revenue_calls'=>'0Всегозапериод',
                                'total_revenue'=>'0Всегозапериод',
                                'ROI'=>'-Всегозапериод',
                                'DRR'=>'-Всегозапериод',
                                'shows_in_spec_placement'=>'-Всегозапериод',
                                'shows_in_waranty_YD'=>'-Всегозапериод',
                                'ration_of_shows_of_spec_or_warantyYD'=>'-Всегозапериод',
                                'num_of_visits_YM'=>'0Всегозапериод',
                                'failures_YM'=>'-Среднеезапериод',
                                'average_length_of_session_YM'=>'0,00Среднеезапериод',
                                'depth_of_view_YM'=>'0,00Среднеезапериод',
                                'goal_YM_one'=>'Всегозапериод',
                                'goal_YM_two'=>'Всегозапериод',

                            ],
                            [
                                'utm_name'=>'cpc',
                                'calls'=>'7',
                                'unique_calls'=>'7',
                                'target_calls'=>'7',
                                'unique_target_calls'=>'7',
                                'calls_in_work_time'=>'7',
                                'online_requests'=>'2',
                                'orders'=>'--',
                                'visits'=>'515',
                                'tags_and_categories'=>'4',
                                'conversion_from_spec_or_garanty'=>'222 / 15',
                                'calls_from_spec_or_garanty'=>'2 / 2',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,90%13,33%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'1,75%',
                                'conversion_from_YD'=>'555',
                                'shows_YD_in_search'=>'62804',
                                'shows_RSY'=>'84865',
                                'costs_YD'=>'31476,60',
                                'costs_in_RSY'=>'4661,70',
                                'costs_to_show_in_search_YD'=>'26814,90',
                                'conversion_from_google_adw'=>'416',
                                'costs_google_adwords'=>'23660,44',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'9',
                                'cost_of_treatment'=>'6126,00',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'--',
                                'failures_YM'=>'--',
                                'average_length_of_session_YM'=>'--',
                                'depth_of_view_YM'=>'--',
                                'goal_YM_one'=>'--',
                                'goal_YM_two'=>'--',

                            ],
                            [
                                'utm_name'=>'[Пустое значение]',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'4',
                                'tags_and_categories'=>'--',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'--',
                                'failures_YM'=>'--',
                                'average_length_of_session_YM'=>'--',
                                'depth_of_view_YM'=>'--',
                                'goal_YM_one'=>'--',
                                'goal_YM_two'=>'--',

                            ],


//                            [
//                                'utm_name'=>' ',
//                                'calls'=>'8Всегозапериод',
//                                'unique_calls'=>'8Всегозапериод',
//                                'target_calls'=>'8Всегозапериод',
//                                'unique_target_calls'=>'8Всегозапериод',
//                                'calls_in_work_time'=>'8Всегозапериод',
//                                'online_requests'=>'2Всегозапериод',
//                                'orders'=>'0Всегозапериод',
//                                'visits'=>'519Всегозапериод',
//                                'tags_and_categories'=>'4Всегозапериод',
//                                'conversion_from_spec_or_garanty'=>'222/15Всегозапериод',
//                                'calls_from_spec_or_garanty'=>'2/2Всегозапериод',
//                                'conversion_to_calls_from_spec_or_garanty'=>'00Всегозапериод',
//                                'conversion_to_orders'=>'-Всегозапериод',
//                                'conversion_to_treatment'=>'1,93%Всегозапериод',
//                                'conversion_from_YD'=>'555Всегозапериод',
//                                'shows_YD_in_search'=>'62804Всегозапериод',
//                                'shows_RSY'=>'84865Всегозапериод',
//                                'costs_YD'=>'31476,60Всегозапериод',
//                                'costs_in_RSY'=>'4661,70Всегозапериод',
//                                'costs_to_show_in_search_YD'=>'26814,90Всегозапериод',
//                                'conversion_from_google_adw'=>'416Всегозапериод',
//                                'costs_google_adwords'=>'23660,44Всегозапериод',
//                                'num_of_sales'=>'0Всегозапериод',
//                                'conversion_from_treatment_to_sale'=>'-Всегозапериод',
//                                'cost_of_sale_CAC'=>'Всегозапериод',
//                                'treatment'=>'10Всегозапериод',
//                                'cost_of_treatment'=>'5513,70Всегозапериод',
//                                'orders_on_calls'=>'0Всегозапериод',
//                                'revenue_calls'=>'0Всегозапериод',
//                                'total_revenue'=>'0Всегозапериод',
//                                'ROI'=>'-Всегозапериод',
//                                'DRR'=>'-Всегозапериод',
//                                'shows_in_spec_placement'=>'-Всегозапериод',
//                                'shows_in_waranty_YD'=>'-Всегозапериод',
//                                'ration_of_shows_of_spec_or_warantyYD'=>'-Всегозапериод',
//                                'num_of_visits_YM'=>'0Всегозапериод',
//                                'failures_YM'=>'-Среднеезапериод',
//                                'average_length_of_session_YM'=>'0,00Среднеезапериод',
//                                'depth_of_view_YM'=>'0,00Среднеезапериод',
//                                'goal_YM_one'=>'Всегозапериод',
//                                'goal_YM_two'=>'Всегозапериод',
//
//                            ],
//                            [
//                                'utm_name'=>'cpc',
//                                'calls'=>'8',
//                                'unique_calls'=>'8',
//                                'target_calls'=>'8',
//                                'unique_target_calls'=>'8',
//                                'calls_in_work_time'=>'8',
//                                'online_requests'=>'2',
//                                'orders'=>'--',
//                                'visits'=>'515',
//                                'tags_and_categories'=>'4',
//                                'conversion_from_spec_or_garanty'=>'222 / 15',
//                                'calls_from_spec_or_garanty'=>'2 / 2',
//                                'conversion_to_calls_from_spec_or_garanty'=>'0,90%13,33%',
//                                'conversion_to_orders'=>'--',
//                                'conversion_to_treatment'=>'1,94%',
//                                'conversion_from_YD'=>'555',
//                                'shows_YD_in_search'=>'62804',
//                                'shows_RSY'=>'84865',
//                                'costs_YD'=>'31476,60',
//                                'costs_in_RSY'=>'4661,70',
//                                'costs_to_show_in_search_YD'=>'26814,90',
//                                'conversion_from_google_adw'=>'416',
//                                'costs_google_adwords'=>'23660,44',
//                                'num_of_sales'=>'--',
//                                'conversion_from_treatment_to_sale'=>'-',
//                                'cost_of_sale_CAC'=>'--',
//                                'treatment'=>'10',
//                                'cost_of_treatment'=>'5513,00',
//                                'orders_on_calls'=>'--',
//                                'revenue_calls'=>'--',
//                                'total_revenue'=>'--',
//                                'ROI'=>'--',
//                                'DRR'=>'--',
//                                'shows_in_spec_placement'=>'--',
//                                'shows_in_waranty_YD'=>'--',
//                                'ration_of_shows_of_spec_or_warantyYD'=>'',
//                                'num_of_visits_YM'=>'--',
//                                'failures_YM'=>'--',
//                                'average_length_of_session_YM'=>'--',
//                                'depth_of_view_YM'=>'--',
//                                'goal_YM_one'=>'--',
//                                'goal_YM_two'=>'--',
//
//                            ],
//                            [
//                                'utm_name'=>'[Пустое значение]',
//                                'calls'=>'--',
//                                'unique_calls'=>'--',
//                                'target_calls'=>'--',
//                                'unique_target_calls'=>'--',
//                                'calls_in_work_time'=>'--',
//                                'online_requests'=>'--',
//                                'orders'=>'--',
//                                'visits'=>'4',
//                                'tags_and_categories'=>'--',
//                                'conversion_from_spec_or_garanty'=>'-- / --',
//                                'calls_from_spec_or_garanty'=>'-- / --',
//                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
//                                'conversion_to_orders'=>'--',
//                                'conversion_to_treatment'=>'0,00%',
//                                'conversion_from_YD'=>'--',
//                                'shows_YD_in_search'=>'--',
//                                'shows_RSY'=>'--',
//                                'costs_YD'=>'--',
//                                'costs_in_RSY'=>'--',
//                                'costs_to_show_in_search_YD'=>'--',
//                                'conversion_from_google_adw'=>'--',
//                                'costs_google_adwords'=>'--',
//                                'num_of_sales'=>'--',
//                                'conversion_from_treatment_to_sale'=>'-',
//                                'cost_of_sale_CAC'=>'--',
//                                'treatment'=>'--',
//                                'cost_of_treatment'=>'--',
//                                'orders_on_calls'=>'--',
//                                'revenue_calls'=>'--',
//                                'total_revenue'=>'--',
//                                'ROI'=>'--',
//                                'DRR'=>'--',
//                                'shows_in_spec_placement'=>'--',
//                                'shows_in_waranty_YD'=>'--',
//                                'ration_of_shows_of_spec_or_warantyYD'=>'',
//                                'num_of_visits_YM'=>'--',
//                                'failures_YM'=>'--',
//                                'average_length_of_session_YM'=>'--',
//                                'depth_of_view_YM'=>'--',
//                                'goal_YM_one'=>'--',
//                                'goal_YM_two'=>'--',
//
//                            ],




                        ]
                    ]
                ],

               ]
             ]
    ],
    [
        'login'=>'cnn',
        'accountId'=>7100,
        'siteId'=>6603,
        'beginDate'=>'2016-06-15',
        'endDate'=>'2016-06-17',
        'section'=>'UTM-метки',
        'utm_data'=>
        [
            [
                'begin_date'=>'2016-06-16',
                'end_date'=>'2016-06-18',
                'utm_filter'=>'UTM Source',
                'utm_data_to_check'=>
                [
                    [
                        'num_of_results'=>7,
                        'utm_report_data'=>
                        [
                            //'utm_name'=>' ',

                            [
                                'utm_name'=>' ',
                                'calls'=>'41Всегозапериод',
                                'unique_calls'=>'30Всегозапериод',
                                'target_calls'=>'19Всегозапериод',
                                'unique_target_calls'=>'14Всегозапериод',
                                'calls_in_work_time'=>'35Всегозапериод',
                                'online_requests'=>'16Всегозапериод',
                                'orders'=>'0Всегозапериод',
                                'visits'=>'3892Всегозапериод',
                                'tags_and_categories'=>'0Всегозапериод',
                                'conversion_from_spec_or_garanty'=>'0/0Всегозапериод',
                                'calls_from_spec_or_garanty'=>'0/0Всегозапериод',
                                'conversion_to_calls_from_spec_or_garanty'=>'00Всегозапериод',
                                'conversion_to_orders'=>'-Всегозапериод',
                                'conversion_to_treatment'=>'0,90%Всегозапериод',
                                'conversion_from_YD'=>'0Всегозапериод',
                                'shows_YD_in_search'=>'0Всегозапериод',
                                'shows_RSY'=>'0Всегозапериод',
                                'costs_YD'=>'0,00Всегозапериод',
                                'costs_in_RSY'=>'0,00Всегозапериод',
                                'costs_to_show_in_search_YD'=>'0,00Всегозапериод',
                                'conversion_from_google_adw'=>'1188Всегозапериод',
                                'costs_google_adwords'=>'45195,16Всегозапериод',
                                'num_of_sales'=>'0Всегозапериод',
                                'conversion_from_treatment_to_sale'=>'-Всегозапериод',
                                'cost_of_sale_CAC'=>'Всегозапериод',
                                'treatment'=>'35Всегозапериод',
                                'cost_of_treatment'=>'1291,29Всегозапериод',
                                'orders_on_calls'=>'0Всегозапериод',
                                'revenue_calls'=>'0Всегозапериод',
                                'total_revenue'=>'0Всегозапериод',
                                'ROI'=>'-Всегозапериод',
                                'DRR'=>'-Всегозапериод',
                                'shows_in_spec_placement'=>'-Всегозапериод',
                                'shows_in_waranty_YD'=>'-Всегозапериод',
                                'ration_of_shows_of_spec_or_warantyYD'=>'-Всегозапериод',
                                'num_of_visits_YM'=>'8092Всегозапериод',
                                'failures_YM'=>'13,90%Среднеезапериод',
                                'average_length_of_session_YM'=>'217,04Среднеезапериод',
                                'depth_of_view_YM'=>'5,48Среднеезапериод',
                                'goal_YM_one'=>'0Всегозапериод',
                                'goal_YM_two'=>'0Всегозапериод',

                            ],
                            [
                                'utm_name'=>'yandex',
                                'calls'=>'22',
                                'unique_calls'=>'14',
                                'target_calls'=>'11',
                                'unique_target_calls'=>'8',
                                'calls_in_work_time'=>'19',
                                'online_requests'=>'11',
                                'orders'=>'--',
                                'visits'=>'2782',
                                'tags_and_categories'=>'--',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,79%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'22',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'2265',
                                'failures_YM'=>'17,53%',
                                'average_length_of_session_YM'=>'182,61',
                                'depth_of_view_YM'=>'5,40',
                                'goal_YM_one'=>'--',
                                'goal_YM_two'=>'--',

                            ],
                            [
                                'utm_name'=>'google',
                                'calls'=>'19',
                                'unique_calls'=>'16',
                                'target_calls'=>'8',
                                'unique_target_calls'=>'6',
                                'calls_in_work_time'=>'16',
                                'online_requests'=>'4',
                                'orders'=>'--',
                                'visits'=>'1031',
                                'tags_and_categories'=>'--',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'1,16%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'1',
                                'costs_google_adwords'=>'43,33',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'12',
                                'cost_of_treatment'=>'3,00',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'971',
                                'failures_YM'=>'20,49%',
                                'average_length_of_session_YM'=>'190,87',
                                'depth_of_view_YM'=>'4,57',
                                'goal_YM_one'=>'--',
                                'goal_YM_two'=>'--',

                            ],
                            [
                                'utm_name'=>'Realtymax.ru',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'1',
                                'orders'=>'--',
                                'visits'=>'32',
                                'tags_and_categories'=>'--',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'3,13%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'1',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'170',
                                'failures_YM'=>'5,88%',
                                'average_length_of_session_YM'=>'173,42',
                                'depth_of_view_YM'=>'3,69',
                                'goal_YM_one'=>'--',
                                'goal_YM_two'=>'--',

                            ],
                            [
                                'utm_name'=>'mc',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'29',
                                'tags_and_categories'=>'--',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'34',
                                'failures_YM'=>'32,35%',
                                'average_length_of_session_YM'=>'58,91',
                                'depth_of_view_YM'=>'3,21',
                                'goal_YM_one'=>'--',
                                'goal_YM_two'=>'--',

                            ],
                            [
                                'utm_name'=>'Irn.ru',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'12',
                                'tags_and_categories'=>'--',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'--',
                                'failures_YM'=>'--',
                                'average_length_of_session_YM'=>'--',
                                'depth_of_view_YM'=>'--',
                                'goal_YM_one'=>'--',
                                'goal_YM_two'=>'--',

                            ],
                            [
                                'utm_name'=>'Avaho.ru',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'5',
                                'tags_and_categories'=>'--',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'235',
                                'failures_YM'=>'1,28%',
                                'average_length_of_session_YM'=>'395,82',
                                'depth_of_view_YM'=>'9,01',
                                'goal_YM_one'=>'--',
                                'goal_YM_two'=>'--',

                            ],
                            [
                                'utm_name'=>'Avaho.ru#start',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'1',
                                'tags_and_categories'=>'--',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'--',
                                'failures_YM'=>'--',
                                'average_length_of_session_YM'=>'--',
                                'depth_of_view_YM'=>'--',
                                'goal_YM_one'=>'--',
                                'goal_YM_two'=>'--',

                            ],


                        ]
                    ]
                ],


            ]
        ]
    ],
    //node 3
    [
        'login'=>'admin',
        'accountId'=>8678,
        'siteId'=>8875,
        'beginDate'=>'2016-06-24',
        'endDate'=>'2016-07-01',
        'section'=>'UTM-метки',
        'utm_data'=>
        [
            [
                'begin_date'=>'2016-06-24',
                'end_date'=>'2016-07-01',
                'utm_filter'=>'UTM Campaign',
                'utm_data_to_check'=>
                [
                    [
                        'num_of_results'=>4,
                        'utm_report_data'=>
                        [
                            [
                                'utm_name'=>' ',
                                'calls'=>'0Всегозапериод',
                                'unique_calls'=>'0Всегозапериод',
                                'target_calls'=>'0Всегозапериод',
                                'unique_target_calls'=>'0Всегозапериод',
                                'calls_in_work_time'=>'0Всегозапериод',
                                'online_requests'=>'0Всегозапериод',
                                'orders'=>'0Всегозапериод',
                                'visits'=>'11Всегозапериод',
                                'conversion_from_spec_or_garanty'=>'0/0Всегозапериод',
                                'calls_from_spec_or_garanty'=>'0/0Всегозапериод',
                                'conversion_to_calls_from_spec_or_garanty'=>'00Всегозапериод',
                                'conversion_to_orders'=>'-Всегозапериод',
                                'conversion_to_treatment'=>'-Всегозапериод',
                                'conversion_from_YD'=>'0Всегозапериод',
                                'shows_YD_in_search'=>'0Всегозапериод',
                                'shows_RSY'=>'0Всегозапериод',
                                'costs_YD'=>'0,00Всегозапериод',
                                'costs_in_RSY'=>'0,00Всегозапериод',
                                'costs_to_show_in_search_YD'=>'0,00Всегозапериод',
                                'conversion_from_google_adw'=>'0Всегозапериод',
                                'costs_google_adwords'=>'0,00Всегозапериод',
                                'num_of_sales'=>'0Всегозапериод',
                                'conversion_from_treatment_to_sale'=>'-Всегозапериод',
                                'cost_of_sale_CAC'=>'Всегозапериод',
                                'treatment'=>'0Всегозапериод',
                                'cost_of_treatment'=>'-Всегозапериод',
                                'orders_on_calls'=>'0Всегозапериод',
                                'revenue_calls'=>'0Всегозапериод',
                                'total_revenue'=>'0Всегозапериод',
                                'ROI'=>'-Всегозапериод',
                                'DRR'=>'-Всегозапериод',
                                'shows_in_spec_placement'=>'-Всегозапериод',
                                'shows_in_waranty_YD'=>'-Всегозапериод',
                                'ration_of_shows_of_spec_or_warantyYD'=>'-Всегозапериод',
                                'num_of_visits_YM'=>'0Всегозапериод',
                                'failures_YM'=>'-Среднеезапериод',
                                'average_length_of_session_YM'=>'0,00Среднеезапериод',
                                'depth_of_view_YM'=>'0,00Среднеезапериод',
                                'goal_YM_one'=>'Всегозапериод',
                                'goal_YM_two'=>'Всегозапериод',
                                'wtf'=>'',
                            ],
                            [
                                'utm_name'=>'kupit_konditsioner_poisk',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'5',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'--',
                                'failures_YM'=>'--',
                                'average_length_of_session_YM'=>'--',
                                'depth_of_view_YM'=>'--',
                                'goal_YM_one'=>'--',
                                'goal_YM_two'=>'--',
                                'wtf'=>'',
                            ],
                            [
                                'utm_name'=>'konditsioneri_Gree_poisk',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'4',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'--',
                                'failures_YM'=>'--',
                                'average_length_of_session_YM'=>'--',
                                'depth_of_view_YM'=>'--',
                                'goal_YM_one'=>'--',
                                'goal_YM_two'=>'--',
                                'wtf'=>'',
                            ],
                            [
                                'utm_name'=>'mobilniye_konditsionery_poisk',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'1',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'--',
                                'failures_YM'=>'--',
                                'average_length_of_session_YM'=>'--',
                                'depth_of_view_YM'=>'--',
                                'goal_YM_one'=>'--',
                                'goal_YM_two'=>'--',
                                'wtf'=>'',
                            ],
                            [
                                'utm_name'=>'konditsioneri_general_poisk',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'1',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                                'costs_google_adwords'=>'--',
                                'num_of_sales'=>'--',
                                'conversion_from_treatment_to_sale'=>'-',
                                'cost_of_sale_CAC'=>'--',
                                'treatment'=>'--',
                                'cost_of_treatment'=>'--',
                                'orders_on_calls'=>'--',
                                'revenue_calls'=>'--',
                                'total_revenue'=>'--',
                                'ROI'=>'--',
                                'DRR'=>'--',
                                'shows_in_spec_placement'=>'--',
                                'shows_in_waranty_YD'=>'--',
                                'ration_of_shows_of_spec_or_warantyYD'=>'',
                                'num_of_visits_YM'=>'--',
                                'failures_YM'=>'--',
                                'average_length_of_session_YM'=>'--',
                                'depth_of_view_YM'=>'--',
                                'goal_YM_one'=>'--',
                                'goal_YM_two'=>'--',
                                'wtf'=>'',
                            ],

                        ]

                    ],
                ]
            ],

        ]
    ],


];
$I = new AcceptanceTester($scenario);
$I->wantTo('Хочу протестировать отчет по UTM меткам у разных сайтов ');

$login = new \Page\AuthFunctional\AuthFunctional($I);
$utmPage = new \Page\Sources\UTMLabels($I);
$navigate = new \Page\Navigation\Navigation($I);

foreach ($utmDataProvider as $key){
    $login->login($I->getProperty($key['login']), $I->getProperty('psw'));
    $navigate->goToPage($key['accountId'], $key['siteId'], $key['beginDate'], $key['endDate'], $key['section']);
    $utmPage->testSearchUtmLabelsByDates($key['utm_data']);
    $login->logout();
}
