<?php 
//@group utmReports
$utmDataProvider = 
[
    /*
     * Positive tests
     */
    [
    'login'=>'welhome',
    'accountId'=>879,
    'siteId'=>1034,
    'beginDate'=>'2016-06-09',
    'endDate'=>'2016-06-09',
    'section'=>'UTM-метки',
    'utm_data'=>
        [
            [
            'begin_date'=>'2016-06-16',
            'end_date'=>'2016-06-16',
            'utm_filter'=>'UTM Content',
    //        'utm_source'=>'',
    //        'utm_term'=>'',
    //        'utm_medium'=>'',
    //        'utm_content'=>'',
    //        'utm_campaign' => '',
             'utm_data_to_check'=>
                [
                    [                     
                        'num_of_results'=>15,
                        'utm_report_data'=>
                        [
                            [
                                'utm_name'=>' ',
                                'calls'=>'4Всегозапериод',
                                'unique_calls'=>'4Всегозапериод',
                                'target_calls'=>'3Всегозапериод',
                                'unique_target_calls'=>'3Всегозапериод',
                                'calls_in_work_time'=>'4Всегозапериод',
                                'online_requests'=>'0Всегозапериод',
                                'orders'=>'0Всегозапериод',
                                'visits'=>'210Всегозапериод',
                                'conversion_from_spec_or_garanty'=>'0/0Всегозапериод',
                                'calls_from_spec_or_garanty'=>'0/0Всегозапериод',
                                'conversion_to_calls_from_spec_or_garanty'=>'00Всегозапериод',
                                'conversion_to_orders'=>'-Всегозапериод',
                                'conversion_to_treatment'=>'1,43%Всегозапериод',
                                'conversion_from_YD'=>'207Всегозапериод',
                                'shows_YD_in_search'=>'4309Всегозапериод',
                                'shows_RSY'=>'573Всегозапериод',
                                'costs_YD'=>'6951,30Всегозапериод',
                                'costs_in_RSY'=>'19,80Всегозапериод',
                                'costs_to_show_in_search_YD'=>'6931,50Всегозапериод',
                                'conversion_from_google_adw'=>'0Всегозапериод',
                            ],



                            [
                                'utm_name'=>'premium.1',
                                'calls'=>'2',
                                'unique_calls'=>'2',
                                'target_calls'=>'2',
                                'unique_target_calls'=>'2',
                                'calls_in_work_time'=>'2',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'110',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'1,82%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                            ],
                            [
                                'utm_name'=>'premium.2',
                                'calls'=>'2',
                                'unique_calls'=>'2',
                                'target_calls'=>'1',
                                'unique_target_calls'=>'1',
                                'calls_in_work_time'=>'2',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'55',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'1,82%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                            ],
                            [
                                'utm_name'=>'premium.3',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'18',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                            ],
                            [
                                'utm_name'=>'other.1',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'8',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                            ],
                            [
                                'utm_name'=>'other.3',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'4',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                            ],
                            [
                                'utm_name'=>'other.2',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'4',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                            ],
                            [
                                'utm_name'=>'{PTYPE}.{POS}',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'2',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                            ],
                            [
                                'utm_name'=>'none.1',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'2',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                            ],
                            [
                                'utm_name'=>'none.7',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'1',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                            ],
                            [
                                'utm_name'=>'none.6',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'1',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                            ],
                            [
                                'utm_name'=>'none.5',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'1',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                            ],
                            [
                                'utm_name'=>'none.2',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'1',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                            ],
                            [
                                'utm_name'=>'none.16',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'1',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                            ],
                            [
                                'utm_name'=>'none.0',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'1',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                            ],
                            [
                                'utm_name'=>'[Пустое значение]',
                                'calls'=>'--',
                                'unique_calls'=>'--',
                                'target_calls'=>'--',
                                'unique_target_calls'=>'--',
                                'calls_in_work_time'=>'--',
                                'online_requests'=>'--',
                                'orders'=>'--',
                                'visits'=>'1',
                                'conversion_from_spec_or_garanty'=>'-- / --',
                                'calls_from_spec_or_garanty'=>'-- / --',
                                'conversion_to_calls_from_spec_or_garanty'=>'0,00%0,00%',
                                'conversion_to_orders'=>'--',
                                'conversion_to_treatment'=>'0,00%',
                                'conversion_from_YD'=>'--',
                                'shows_YD_in_search'=>'--',
                                'shows_RSY'=>'--',
                                'costs_YD'=>'--',
                                'costs_in_RSY'=>'--',
                                'costs_to_show_in_search_YD'=>'--',
                                'conversion_from_google_adw'=>'--',
                            ],







                        ]
                    ],
                ]
            ],

        ],
    
    ],
];
$I = new AcceptanceTester($scenario);
$I->wantTo('Хочу протестировать отчет по UTM меткам ');

$login = new \Page\AuthFunctional\AuthFunctional($I);
$utmPage = new \Page\Sources\UTMLabels($I);
$navigate = new \Page\Navigation\Navigation($I);

foreach ($utmDataProvider as $key){
    $login->login($I->getProperty($key['login']), $I->getProperty('psw'));
    $navigate->goToPage($key['accountId'], $key['siteId'], $key['beginDate'], $key['endDate'], $key['section']);
    $utmPage->testSearchUtmLabelsByDates($key['utm_data']);
    $login->logout();
}
